apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycollection3-coll-47b6c1ee9d434c66bb445775116fb7d0-depl
  labels:
    app: mycollection3-coll-47b6c1ee9d434c66bb445775116fb7d0
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycollection3-coll-47b6c1ee9d434c66bb445775116fb7d0
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: mycollection3-coll-47b6c1ee9d434c66bb445775116fb7d0
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: mycollection3-coll-47b6c1ee9d434c66bb445775116fb7d0
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:mycollection3-coll-47b6c1ee9d434c66bb445775116fb7d0
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping